name: Gridgain-Release
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release Version"
        required: true
        default: "X.Y.Z[-(alpha|beta|xxx)]"
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Set versions
        run: scripts/update-versions.sh ${{ inputs.release_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
      - name: Publish package
        run: mvn deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
